- Admin:
    - AdGuard:
        - href: https://${ADGUARD_SERVER_PREFIX}.${SERVER_NAME}
    - Router:
        - href: http://192.168.8.1
    - Jellyfin:
        - href: https://${TORTUGA_SERVER_PREFIX}.${SERVER_NAME}
    - qBittorrent:
        - href: http://${blackpearl_SERVER_PREFIX}.${SERVER_NAME}
