- Infra:
    - Caddy:
        icon: caddy.png
        description: Reverse proxy
        server: my-docker
        container: {{HOMEPAGE_VAR_CADDY_CONTAINER}}
        widget:
          type: caddy
          url: http://{{HOMEPAGE_VAR_CADDY_CONTAINER}}:2019

- Media:
    - Tortuga:
        icon: jellyfin.png
        href: https://{{HOMEPAGE_VAR_TORTUGA_SERVER_PREFIX}}.{{HOMEPAGE_VAR_SERVER_NAME}}
        description: Movies and TV
        server: my-docker
        container: {{HOMEPAGE_VAR_TORTUGA_CONTAINER}}
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_TORTUGA_CONTAINER}}:8096
          key: {{HOMEPAGE_VAR_TORTUGA_API_KEY}}

    - Blackpearl:
        icon: qbittorrent.png
        href: https://{{HOMEPAGE_VAR_BLACKPEARL_SERVER_PREFIX}}.{{HOMEPAGE_VAR_SERVER_NAME}}
        description: Downloads
        server: my-docker
        container: {{HOMEPAGE_VAR_BLACKPEARL_CONTAINER}}
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_BLACKPEARL_CONTAINER}}:8080
          username: {{HOMEPAGE_VAR_BLACKPEARL_USERNAME}}
          password: {{HOMEPAGE_VAR_BLACKPEARL_PASSWORD}}

    - Sonarr:
        icon: sonarr.png
        href: https://{{HOMEPAGE_VAR_SONARR_SERVER_PREFIX}}.{{HOMEPAGE_VAR_SERVER_NAME}}
        description: TV management
        server: my-docker
        container: {{HOMEPAGE_VAR_SONARR_CONTAINER}}
        widget:
          type: sonarr
          url: http://{{HOMEPAGE_VAR_SONARR_CONTAINER}}:8989
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
