title: voidroute
theme: dark
color: zinc
headerStyle: clean
layout:
  Infra:
    style: row
    columns: 1
  Media:
    style: row
    columns: 4
    header: false

background:
  image: /images/bg.jpg
  opacity: 20

cardBlur: md
statusStyle: dot
hideVersion: true
