- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    tempmin: 0
    tempmax: 100
    uptime: true
    units: metric
    refresh: 3000
    diskUnits: bytes
    network: true

- datetime:
    locale: hr
    text_size: xl
    format:
      dateStyle: long
      timeStyle: long

- openmeteo:
    label: Osijek
    latitude: 45.5544
    longitude: 18.6624
    timezone: Europe/Zagreb
    units: metric

- calendar:
    view: agenda
    maxEvents: 10
    showTime: true
    previousDays: 3
    integrations:
      - type: sonarr
        service_group: Media
        service_name: Sonarr
        color: teal
        params:
          unmonitored: true
      - type: radarr
        service_group: Media
        service_name: Radarr
        color: orange
        params:
          unmonitored: true
