name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - infra/**

env:
  ENV_FILE: ${{ vars.SERVER_BASE_PATH }}/.env

jobs:
  deploy:
    runs-on: self-hosted
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write .env
        uses: ./.github/actions/write-env
        with:
          SERVER_NAME: ${{ vars.SERVER_NAME }}
          SERVER_BASE_PATH: ${{ vars.SERVER_BASE_PATH }}
          DOCKER_NETWORK: ${{ vars.DOCKER_NETWORK }}
          CADDY_CONTAINER: ${{ vars.CADDY_CONTAINER }}
          HOMEPAGE_CONTAINER: ${{ vars.HOMEPAGE_CONTAINER }}
          TORTUGA_CONTAINER: ${{ vars.TORTUGA_CONTAINER }}
          BLACKPEARL_CONTAINER: ${{ vars.BLACKPEARL_CONTAINER }}
          SONARR_CONTAINER: ${{ vars.SONARR_CONTAINER }}
          HOMEPAGE_SERVER_PREFIX: ${{ vars.HOMEPAGE_SERVER_PREFIX }}
          ADGUARD_SERVER_PREFIX: ${{ vars.ADGUARD_SERVER_PREFIX }}
          TORTUGA_SERVER_PREFIX: ${{ vars.TORTUGA_SERVER_PREFIX }}
          BLACKPEARL_SERVER_PREFIX: ${{ vars.BLACKPEARL_SERVER_PREFIX }}
          SONARR_SERVER_PREFIX: ${{ vars.SONARR_SERVER_PREFIX }}
          VOIDROUTE_VPN_SUBNET: ${{ vars.VOIDROUTE_VPN_SUBNET }}
          MEDIA_ROOT: ${{ vars.MEDIA_ROOT }}
          TZ: ${{ vars.TZ }}
          PUID: ${{ vars.PUID }}
          PGID: ${{ vars.PGID }}
          PG_CONTAINER: ${{ vars.PG_CONTAINER }}
          PG_VOLUME: ${{ vars.PG_VOLUME }}
          PG_PORT_BIND: ${{ vars.PG_PORT_BIND }}
          TORTUGA_API_KEY: ${{ secrets.TORTUGA_API_KEY }}
          BLACKPEARL_USERNAME: ${{ secrets.BLACKPEARL_USERNAME }}
          BLACKPEARL_PASSWORD: ${{ secrets.BLACKPEARL_PASSWORD }}
          SONARR_API_KEY: ${{ secrets.SONARR_API_KEY }}
          POSTGRES_ADMIN_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}

      - name: Ensure docker network exists
        run: |
          source "$ENV_FILE"
          docker network inspect "$DOCKER_NETWORK" >/dev/null 2>&1 || \
          docker network create "$DOCKER_NETWORK"

      - name: Deploy stack
        run: |
          cd infra
          docker compose --env-file "$ENV_FILE" pull
          docker compose --env-file "$ENV_FILE" up -d --remove-orphans

          docker image prune -f
          docker container prune -f

      - name: Status
        run: docker compose -f infra/docker-compose.yml --env-file "$ENV_FILE" ps
